version: "3.1"
services:
  mysql:
    container_name: mysql-watch2 # container name
    image: mysql:5.7 # images version
    ports:
      - "3306:3306"
    environment:
      # MYSQL_USER: ${MYSQL_USER}
      # MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      # MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
      # MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_ROOT_PASSWORD: "xiaoyan106"
      MYSQL_DATABASE: ‘watch'
    volumes:
      # - "${MYSQL_DIR}/data:/var/lib/mysql"           # data
      # - "${MYSQL_DIR}/config:/etc/mysql/conf.d"      # config
      - "./mysql/data:/var/lib/mysql" # data
      - "./mysql/config:/etc/mysql/conf.d" # config
  app-deno:
    container_name: app-deno
    build: .
    volumes:
      - /etc/localtime:/etc/localtime
    # - /wwwroot/watch:/usr/src/app
    ports:
      - "2000:2000"
    # links:
    #   - mysql:mysql
    # depends_on:
    #   - mysql
  nginx:
    # restart: always
    image: nginx
    ports:
      - 8088:80
    volumes:
      - ./docker/etc/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./dist/:/usr/share/nginx/note/
      # - ./static/:/static/
    depends_on:
      - app-deno
